### PR TITLE
Text: Use U+2004 THREE-PER-EM SPACE for מקף

### PR DESCRIPTION
**Pull request by SLaks**
This disables justification, preventing text from shifting as you toggle

### CODE REVIEW

**Comment by akivajgordon** [comment]
My understanding of the change here is that it eliminates some of the additional whitespace between מקף-separated words. If that's the case, I'm not in favor of this change because I think it does not match the reality. In the Torah, מקף-separated words are spaced just like every other word. Is that not the case?

**Comment by akivajgordon** [comment]
I am aware that there is some jitter when swapping between Chumash-side vs. Torah-side, but I don't find it overly disorienting, and I haven't come up with a better solution. I guess in theory if the words could be animated over, say, a 0.15s timeframe, that would be a little less jarring, but it sounds like a technical challenge.

**Comment by SLaks** [comment]
That's a good point.

As an alternative fix, I tried inserting a regular space after each מקף on the חומש side.
That completely fixes this issue, but makes the חמוש side a bit weird.

WDYT?

I should be possible to animate this by wrapping מקףs in their own `<span>`s and animating their `max-width` to `0`, but I'm not going to try that now

**Comment by akivajgordon** [comment]
I'd try to stay true to what one would find in תיקון סימנים, for example. I'd bet if you superimpose those two columns from a paper tikkun, you'd see similar offsets between some of the words as one sees in tikkun.io. Just the nature of the beast.

Even if we were to animate, I wouldn't limit it to מקף, since there is also פסק, סוף פסוק, etc. 

I really appreciate your input and effort on this one, but I think I'm going to close this as a "won't do" for now. More than happy to reopen if you have any other thoughts or want to take a stab at a different solution.

**Comment by SLaks** [comment]
> I'd bet if you superimpose those two columns from a paper tikkun, you'd see similar offsets between some of the words as one sees in tikkun.io. Just the nature of the beast.

Of course (but it matters less in print)

> Even if we were to animate, I wouldn't limit it to מקף, since there is also פסק, סוף פסוק, etc.

Of course; I would animate anything that appears in only one version.

> I really appreciate your input and effort on this one, but I think I'm going to close this as a "won't do" for now. More than happy to reopen if you have any other thoughts or want to take a stab at a different solution.

Makes sense.

I might try animating later, but that's a much lower priority, so I may never get to it.

**Pull request closed without merging**
