### PR TITLE
Rewrite backend to use @hebcal

### PR DESCRIPTION
**Pull request by SLaks**
I'm sending this PR to give you an early look at how I'm implementing my [calendar-based redesign](https://docs.google.com/document/d/17fsv4TVKUVNfSnh5wMu_FyDUKRkrtQo76KVLsa9QA1g/edit).

Can you please take a quick look and let me know if you have any feedback?

This PR includes full logic (and test coverage) to calculate the days and leinings to display.

Next, I will write the view model class that will power the infinite scroller and Aliyah display.

I will then port first the display, then the picker, to be powered by the new models.

### CODE REVIEW

**Comment by SLaks** [comment]
If you want, I can move commits from this PR into standalone PRs.

The commits include full descriptions.

**Comment by SLaks** [comment]
This now has a working prototype!  (still not ready to merge)

https://tikkun.io/pr-preview/pr-129/

## What works

 - Will default to the upcoming leining (currently יום כיפור שחרית, which is a great test case)
 - For ימים טובים, will only show pages from the יום טוב, _including מפטיר_ (new feature!), showing how many עמודים were skipped
 - It will label the end of an עלייה if no other עלייה starts there (new feature!), for יום טוב
 - If you select a פרשה from the picker, it will jump to that פרשה as laid out for the current Hebrew calendar year.
   - For example, select בהר to see it laid out as a double פרשה only.
   - Select תרומה to see no שישי.

## TODO

 - URL parsing
 - Rewrite the picker from scratch (probably using React)
 - Rewrite the navigation bar from scratch, including links to מפטיר / הפטרה when applicable.  I will likely use React here too
 - Unit tests for the view model layer
 - Fix header labelling on scroll

## How to handle this PR

You have 3 options:

 1. I can continue to develop the entire feature in this PR, then merge it all at once
 2. You can merge this PR as-is into a temporary branch, and merge followup PRs into that branch as they become ready, then merge that branch into `develop` when everything is done.
 3. I can split this into multiple smaller PRs, then merge them into a temporary branch as above:
     1. Model layer (generator.ts, model-types.ts, and related files)
     2. View model layer (scroll-view-model.ts and related files)
     3. UI changes (For now, just https://github.com/akivajgordon/tikkun.io/pull/129/commits/493ba86fc5b04e3fdf4d8687570bc4905e9d6f48)
     4. New URL handling
     5. (not yet written) Navigation bar (which will have its own view model that can go in a separate PR)
     6. New picker UI

How do you want to proceed?

**Comment by SLaks** [comment]
I now have easily-readable golden tests of the underlying model information

Do you have time to take a look, and find any mistakes, or other corner cases that I should add tests for?

 - https://github.com/SLaks/tikkun.io/blob/calendar-rewrite-full/src/calendar-model/generator.test.ts.md
   - This computes the structure of leinings that you can navigate through (see https://github.com/SLaks/tikkun.io/tree/calendar-rewrite-full/src/calendar-model#calendar-based-model for details)
   - The עליות come from @hebcal, and are presumably correct; I'm primarily asking about the groupings.
- https://github.com/SLaks/tikkun.io/blob/calendar-rewrite-full/src/view-model/aliyah-labeller.test.ts.md
   - This tests the actual contents that you will see in the Tikkun when you select any particular run from the previous test.
   - The test only includes lines that are labelled as an עלייה.
   - This tests both which עליות are displayed and exactly how they get labelled.
   - When you select a פרשה, it will scroll through all of חומש, so the test only covers עמודים that include that פרשה.  This may still include labels from surrounding פרשיות.

I will now work on the model for the navigation bar, which will get its own snapshot tests.

Related question: Do you want to only deploy this rewrite after you add JSON files for הפטרות (and other מגילות)?
If not, I will need to temporarily hide or disable UI that links to unsupported scrolls.

**Comment by SLaks** [comment]
This now has full feature parity with the original version; I updated the picker UI to be backed by the new calendar model and deleted all JSON files except for TOC and pages for `esther` and `torah`.

You can try it at https://tikkun.io/pr-preview/pr-129/.  Note that it's blocked by hebcal/hebcal-leyning#462

If you want, you can merge this and deploy it to production (once that issue is fixed), or set a new branch for a `beta.tikkun.io`.

WDYT of the UX, and, in particular, the labelling (which can probably use some work)?

**Comment by SLaks** [comment]
Next steps:

 - Write UI unit tests using vitest
 - Rewrite the top bar to include links and better layout
 - Entirely rewrite the picker UI (see open questions in #135 about how that should be structured)

**Comment by SLaks** [comment]
Also, this links to all 5 מגילות (modulo hebcal/hebcal-leyning#463).

Before we can release this, we must either add JSON pages & TOCs for מגילות, or temporarily exclude them from the picker.

This also supports הפטרות, but it doesn't render any links to them (until I rewrite the navbar), so there is nothing to hide there.

**Comment by SLaks** [comment]
Should I make further UI changes (new top bar and new picker) in this branch, or should I open a separate PR for them? (do you want to land these changes with the existing UI first?)

I can easily rebase in either direction after the fact.

**Comment by SLaks** [comment]
Both hebcal bugs have been fixed, and I pushed the fixes.

Current plans/next steps:

 - This branch is ready to release (possibly as a beta), except that it includes broken links to מגילות.
   - If you want to release, you can add JSON for מגילות, or I can temporarily hide those links.
   - We may also want to review and tweak titles.
   - This PR no longer supports `/p/` and `/h/` links (it uses a new URL format instead).  Do you think I need to maintain support for existing bookmarks?
 - If you want, I can (fairly easily) split this into 3-5 (or so) more-focused PRs for ease of reviewing.
 - I will add Vitest browser-side test coverage, and possibly some further refactors or minor features, to this PR (or PRs that I split it into)
 - I will rewrite the top bar and picker in a separate PR to keep this one functional.

What do you want to do next?

**Comment by akivajgordon** [comment]
@SLaks Are you intending to make more changes to this PR? Or should I give it a review and merge?

**Comment by SLaks** [comment]
Not at the moment; I'll send followup PRs in the coming weeks to fix scrolling, filter out unavailable books, etc.

**Comment by SLaks** [comment]
This is ready to merge.

I will work on scrolling, labelling, and the top bar in separate PRs.

**Pull request merged**
