### PR TITLE
Replace schedule.json with Hebcal

### PR DESCRIPTION
**Pull request by SLaks**
See last commit description.

This includes my other PRs.

### CODE REVIEW

**Comment by SLaks** [comment]
To clarify, this PR as-is is mostly useless; it replaces a small JSON file with a much bigger dependency.

However, it's a first step to using HebCal to do more.

For example:

 - I can replace `parshiyot.json` and `alyiot.json` with https://github.com/hebcal/hebcal-leyning, which already contains a complete list of עליות and their locations.
 - I can include ימים טובים in the upcoming section in the picker (this should be extremely simple)
 - I can rewrite the picker to show a list of leining days in order for an arbitrary year (replacing the separate sections for פרשיות and ימים טובים)
 - I can start implementing הפטרות
 - I can display עליות based on the actual calendar (eg, collapsing שביעי when there are 3 ספרי תורה).
    - Note that this would mean making the main display, not just the picker, aware of the selected/current calendar year.
    - I can also add a link to מפטיר when מפטיר is elsewhere.

Related cleanups (I think these can actually be done without HebCal as well):

 - I can replace `table-of-contents-holydays.json` with the same information from `table-of-contents.json`
    -  Is there a reason this exists as a separate file? Because they use the same pagination as the regular Torah, it seems to be entirely a duplicate of the base TOC.
 - I can entirely remove the separate `pages/**` for holidays, and instead render the requisite pages from the regular `pages/torah/` with the Holiday עליות.

What approaches would you like to take?

**Comment by akivajgordon** [comment]
@SLaks here too, you can merge back from `develop` and resolve the conflicts and re-push so that I can take a look.

As for your comments:

I'm more than happy to get this extra functionality from Hebcal and throw away the JSON files that I made. I think that's a value add here. Introducing it in this PR is a good start.

Regarding the `table-of-contents`, I think you're right. I don't see any reason we specifically need that one for the holidays. It gives the same information as the regular one.

I guess the only reason I kept the `pages/**` was that it limits where you can scroll to when you choose, e.g., Rosh Hashanah. It sort of gives you a mini-tikkun of just the Rosh Hashanah reading and nothing more, so when you scroll to the end, you don't continue into פרשת חיי שרה, for example. I'm mixed on this decision... often, I like it because it keeps me from scrolling away to other content by accident (especially when my kids grab the phone from me, they like scrolling 🤷‍♂️), but every now and then it's nice to know the surrounding context.

I know that we can provide the same scrolling limitation by using the page numbers from the full tikkun, but this way was just convenient at the time without the app needing to know too much. With respect to changing the internal way of limiting the scrolling, I'm open to changing the way we do that. As for whether or not we should be limiting the scrolling in the first place, like I said, I'm not sure which is the better way. Feel free to convince me on one side or the other.

**Comment by SLaks** [comment]
I'm not really ready to merge this; I will probably improve the code some more first.

Do you have a preference between smaller-grained PRs vs. fewer PRs? (eg, should I drop more JSON files and or rewrite the picker UI in separate PRs?)

**Comment by akivajgordon** [comment]
I prefer smaller PRs. More of them is ok. My experience tells me that stuff gets lost/overlooked in larger PRs.

**Comment by akivajgordon** [comment]
I marked the PR as draft for now since you said you're not ready to merge it. You should be able to update that status when you're ready for review. Or explicitly add me as a reviewer as a signal that you're ready.

**Comment by SLaks** [comment]
I wrote https://docs.google.com/document/d/17fsv4TVKUVNfSnh5wMu_FyDUKRkrtQo76KVLsa9QA1g/edit with a full proposal for how to redesign this to be entirely backed by a calendar.

WDYT?

I'm also sharing it with other בעלי קריאה I know to get UX feedback; feel free to share it around your circles to get more feedback.

I'm ready to start implementing this.

**Pull request closed without merging**
